{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 4", "trace": "self = <jst_rebuild.foo.test_file.TestRun object at 0x0000000005171C50>\n\n    @allure.feature('测试1号')\n    def test_01(self):\n        a= 5\n        b= 4\n>       assert  a==b\nE       assert 5 == 4\n\ntest_file.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "653299dc-4369-47f8-8bce-9108682ea249-attachment.txt", "type": "text/plain"}], "start": 1596523339330, "stop": 1596523339331, "uuid": "99b27e61-f43d-4915-b6a9-3140f85a695a", "historyId": "0148ccc8208be825f7d07a3d35e8d366", "testCaseId": "bcfc8a321967fc71084e27e143e50f51", "fullName": "foo.test_file.TestRun#test_01", "labels": [{"name": "feature", "value": "测试1号"}, {"name": "parentSuite", "value": "foo"}, {"name": "suite", "value": "test_file"}, {"name": "subSuite", "value": "TestRun"}, {"name": "host", "value": "WangLiu"}, {"name": "thread", "value": "12672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "foo.test_file"}]}