{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 4", "trace": "self = <jst_rebuild.foo.test_file.TestRun object at 0x000000000517CB00>\n\n    def test_01(self):\n        a= 5\n        b= 4\n>       assert  a==b\nE       assert 5 == 4\n\ntest_file.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "4d3ce3e5-ce03-45a7-a858-c4d1eb0c3df9-attachment.txt", "type": "text/plain"}], "start": 1596523229408, "stop": 1596523229409, "uuid": "012d4a8f-267c-4259-ac18-ec5fc1f7a8d9", "historyId": "0148ccc8208be825f7d07a3d35e8d366", "testCaseId": "bcfc8a321967fc71084e27e143e50f51", "fullName": "foo.test_file.TestRun#test_01", "labels": [{"name": "parentSuite", "value": "foo"}, {"name": "suite", "value": "test_file"}, {"name": "subSuite", "value": "TestRun"}, {"name": "host", "value": "WangLiu"}, {"name": "thread", "value": "12128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "foo.test_file"}]}